name: Continuous Delivery Workflow

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Package delivery artifact
        uses: actions/upload-artifact@v5
        with:
          name: projetozipado
          path: |
            **/*.py
            **/*.html
            **/*.css
            **/*.java
            **/*.js
            **/*.yml
            **/*.json
            **/*.mjs
            **/*.cjs
            **/*.md
            **/*.venv
            **/*.env
            
  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: projetozipado
          path: ./artifact

      - name: Display structure of downloaded files
        run: ls -R ./artifact